-- MySQL Script generated by MySQL Workbench
-- Fri Feb 24 15:28:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Template
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Template
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Template` DEFAULT CHARACTER SET utf8 ;
USE `Template` ;

-- -----------------------------------------------------
-- Table `Template`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Template`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(124) NOT NULL,
  `lastname` VARCHAR(124) NOT NULL,
  `email` VARCHAR(248) NOT NULL,
  `password` VARCHAR(1024) NOT NULL,
  `admin` TINYINT NOT NULL,
  `image_user` VARCHAR(1024) NOT NULL,
  `date` VARCHAR(124) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Template`.`component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Template`.`component` (
  `idcomponent` INT NOT NULL AUTO_INCREMENT,
  `component_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcomponent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Template`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Template`.`image` (
  `idimage` INT NOT NULL AUTO_INCREMENT,
  `image_name` VARCHAR(2048) NOT NULL,
  `component_idcomponent` INT NOT NULL,
  PRIMARY KEY (`idimage`, `component_idcomponent`),
  INDEX `fk_image_component_idx` (`component_idcomponent` ASC) VISIBLE,
  CONSTRAINT `fk_image_component`
    FOREIGN KEY (`component_idcomponent`)
    REFERENCES `Template`.`component` (`idcomponent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Template`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `Template`;
INSERT INTO `Template`.`user` (`iduser`, `firstname`, `lastname`, `email`, `password`, `admin`, `image_user`, `date`) VALUES (1, 'Vincent', 'ROUGET', 'vincent.rouget86@gmail.com', '$argon2id$v=19$m=65536,t=5,p=1$hVXbi5Jyajd9A3YpBn45Qw$h4s4NYz5wHMUAhkJ9vkKaUadXnyzxUPuBTep34gEHsY', 1, 'black_hole.jpg', '2023/02/10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Template`.`component`
-- -----------------------------------------------------
START TRANSACTION;
USE `Template`;
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (1, 'logo');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (2, 'banniere');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (3, 'introduction');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (4, 'contenant1');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (5, 'contenant2');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (6, 'contenant3');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (7, 'contenant4');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (8, 'vignette1');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (9, 'vignette2');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (10, 'vignette3');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (11, 'vignette4');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (12, 'slider1');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (13, 'slider2');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (14, 'slider3');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (15, 'slider4');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (16, 'video1');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (17, 'video2');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (18, 'video3');
INSERT INTO `Template`.`component` (`idcomponent`, `component_name`) VALUES (19, 'video4');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Template`.`image`
-- -----------------------------------------------------
START TRANSACTION;
USE `Template`;
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (1, 'logo.jpg', 1);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (2, 'banniere.jpg', 2);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (3, 'commune2.jpg', 3);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (4, 'hiver3.jpg', 3);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (5, 'facade.jpg', 3);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (6, 'suite_parentale2.jpg', 3);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (30, 'commune2.jpg', 12);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (31, 'commune6.jpg', 12);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (32, 'commune5.jpg', 12);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (33, 'chambre2-1.jpg', 12);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (34, 'suite_parentale1.jpg', 12);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (35, 'suite_parentale5.jpg', 12);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (36, 'suite_parentale9.jpg', 12);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (37, 'commune1.jpg', 12);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (38, 'suite_parentale7.jpg', 12);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (41, 'facade.jpg', 13);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (42, 'ete1.jpg', 13);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (43, 'hiver3.jpg', 13);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (44, 'hiver4.jpg', 13);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (47, 'salle2.jpg', 14);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (48, 'salle3.jpg', 14);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (49, 'salle4.jpg', 14);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (9, 'chambre1-1.jpg', 4);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (10, 'chambre1-3.jpg', 4);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (11, 'chambre1-4.jpg', 4);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (12, 'chambre1-5.jpg', 4);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (13, 'chambre2-2.jpg', 4);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (14, 'chambre2-1.jpg', 4);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (15, 'chambre2-3.jpg', 4);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (16, 'suite_parentale2.jpg', 5);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (17, 'suite_parentale9.jpg', 5);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (18, 'suite_parentale10.jpg', 5);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (19, 'suite_parentale5.jpg', 5);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (20, 'twin1.jpg', 6);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (21, 'twin2.jpg', 6);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (22, 'twin3.jpg', 6);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (23, 'twin4.jpg', 6);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (24, 'facade.jpg', 6);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (25, 'suite_parentale2.jpg', 7);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (26, 'suite_parentale1.jpg', 7);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (27, 'suite_parentale7.jpg', 7);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (28, 'suite_parentale5.jpg', 7);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (29, 'suite_parentale3.jpg', 7);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (39, 'salle1.jpg', 12);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (40, 'commune4.jpg', 12);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (7, 'salle2.jpg', 3);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (8, 'commune5.jpg', 3);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (45, 'hiver1.jpg', 13);
INSERT INTO `Template`.`image` (`idimage`, `image_name`, `component_idcomponent`) VALUES (46, 'hiver2.jpg', 13);

COMMIT;

